# Generated by Django 3.0.6 on 2020-06-09 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('available_for_hire', models.BooleanField(default=False)),
                ('occupation', models.CharField(blank=True, default='', max_length=50)),
                ('category', models.CharField(choices=[('P&T', 'Programming & Technology'), ('G&D', 'Graphics & Design'), ('DM', 'Digital Marketing'), ('W&T', 'Writing & Translation'), ('DE', 'Data Entry'), ('V&M', 'Video & Animation'), ('M&A', 'Music & Audio'), ('B&I', 'Business & Investment'), ('CS', 'Consulting Service'), ('M&P', 'Medical & Pharma'), ('AH', 'Architect Designs'), ('LI', 'Lifestyle'), ('Aud', 'Audit & Taxation'), ('QA', 'Quality Assurance'), ('Eng', 'Engineering Consultancy'), ('OM', 'Organization Management'), ('RP', 'Repair & Technical Support'), ('E&T', 'Education & Teaching')], default='', max_length=40)),
                ('description', models.TextField(default='', max_length=1000, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=13)),
                ('education', models.CharField(blank=True, default='', max_length=24)),
                ('price', models.PositiveIntegerField(blank=True, default='', max_length=12)),
                ('website', models.URLField(blank=True, max_length=250, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('favourite', models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL)),
                ('skills', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='skills')),
            ],
        ),
        migrations.CreateModel(
            name='Hiree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hirees', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('hirer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hirer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signin.Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
