# Generated by Django 3.0.6 on 2020-06-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=''),
        ),
    ]
