# Generated by Django 3.0.6 on 2020-06-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0002_auto_20200609_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
