# Generated by Django 3.0.6 on 2020-06-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0002_auto_20200605_1315'),
        ('signin', '0002_auto_20200605_1259'),
    ]

    operations = [
    ]
