# Generated by Django 3.0.6 on 2020-06-06 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0004_hiree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiree',
            old_name='users',
            new_name='hirees',
        ),
        migrations.RenameField(
            model_name='hiree',
            old_name='current_user',
            new_name='hirer',
        ),
    ]
