# Generated by Django 3.0.6 on 2020-06-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0003_merge_20200605_1657'),
        ('signin', '0005_auto_20200606_1150'),
        ('signin', '0003_merge_20200605_1758'),
    ]

    operations = [
    ]
