# Generated by Django 3.0.6 on 2020-08-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0006_auto_20200609_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(default='', null=True, upload_to='cover_images/%Y%m%d'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='profile_pictures/%Y%m%d'),
        ),
    ]
