# Generated by Django 3.0.6 on 2020-06-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0006_merge_20200606_1812'),
        ('signin', '0006_merge_20200606_1742'),
    ]

    operations = [
    ]
