# Generated by Django 3.0.6 on 2020-08-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0007_auto_20200807_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='cover_images/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profile_pictures/%Y%m%d'),
        ),
    ]
