# Generated by Django 3.0.6 on 2020-06-08 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0008_profile_favourite'),
        ('signin', '0008_comment'),
    ]

    operations = [
    ]
