# Generated by Django 3.0.6 on 2020-06-01 15:31

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='seller',
            name='education',
            field=models.CharField(choices=[('Currently Studying', 'Currently Studying'), ('Under SLC', 'Under SLC'), ('SLC', 'SLC'), ('Intermediate', 'Intermediate'), ('Bachelor', 'Bachelor'), ('Masters', 'Masters')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='occupation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='personal_website',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='profile_images/%Y%m%d'),
        ),
        migrations.AddField(
            model_name='seller',
            name='skills',
            field=models.CharField(choices=[('Programming & Tech', 'Programming & Tech'), ('Graphics & Design', 'Graphics & Design'), ('Digital Marketing', 'Digital Marketing'), ('Writing & Translation', 'Writing & Translation'), ('Data Entry', 'Data Entry'), ('Video & Animation', 'Video & Animation'), ('Music & Sound', 'Music & Sound'), ('Business & Life Style', 'Business & Life Style'), ('Engineering', 'Engineering'), ('Teaching & Counselling', 'Teaching & Counselling'), ('Audit & Accountancy', 'Audit & Accountancy')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
